# Generated by Django 6.0.4 on 2026-04-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmojinaryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('movie', 'Movie'), ('phrase', 'Phrase'), ('song', 'Song'), ('tvshow', 'TV Show'), ('thing', 'Thing')], default='thing', max_length=10)),
                ('difficulty', models.PositiveIntegerField(default=1, help_text='1=easy, 2=medium, 3=hard')),
            ],
            options={
                'ordering': ['category', 'text'],
            },
        ),
    ]
