apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: marco-silva
data:
  DJANGO_SETTINGS_MODULE: website.settings
  POSTGRES_HOST: postgres
  POSTGRES_NAME: marcosilva
  POSTGRES_USER: marcosilva
  ALLOWED_HOSTS: marco-silva.com,www.marco-silva.com
  STATIC_ROOT: /var/www/marco-silva.com/static
  MEDIA_ROOT: /var/www/marco-silva.com/media
  PLANZ_PASSWORD: changeme
  GOOGLE_CALENDAR_ID: ""
