# Generated by Django 6.0.4 on 2026-04-26 21:38

import django.db.models.deletion
import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0013_alter_watermark_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_file', models.FileField(blank=True, help_text='Original camera RAW file (CR3, ARW, NEF, etc.)', upload_to=photos.models.raw_upload_path, verbose_name='RAW file')),
                ('watermarked_image', models.ImageField(blank=True, upload_to=photos.models.watermarked_upload_path, verbose_name='watermarked image')),
                ('camera_make', models.CharField(blank=True, max_length=100, verbose_name='camera make')),
                ('camera_model', models.CharField(blank=True, max_length=100, verbose_name='camera model')),
                ('lens', models.CharField(blank=True, max_length=200, verbose_name='lens')),
                ('focal_length', models.CharField(blank=True, max_length=20, verbose_name='focal length')),
                ('aperture', models.CharField(blank=True, max_length=20, verbose_name='aperture')),
                ('shutter_speed', models.CharField(blank=True, max_length=20, verbose_name='shutter speed')),
                ('iso', models.PositiveIntegerField(blank=True, null=True, verbose_name='ISO')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('location_name', models.CharField(blank=True, max_length=200, verbose_name='location name')),
                ('is_for_sale', models.BooleanField(default=False, verbose_name='available for sale')),
                ('price_raw', models.DecimalField(blank=True, decimal_places=2, help_text='Price for the RAW file download.', max_digits=8, null=True, verbose_name='RAW price')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='processing status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='photologue.photo', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'photo extension',
                'verbose_name_plural': 'photo extensions',
            },
        ),
    ]
