# Generated by Django 6.0.4 on 2026-04-27 14:09

import django.db.models.deletion
import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0013_alter_watermark_image'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoextension',
            name='web_image',
            field=models.ImageField(blank=True, upload_to=photos.models.web_upload_path, verbose_name='web-optimized image'),
        ),
        migrations.CreateModel(
            name='GalleryExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_type', models.CharField(choices=[('curated', 'Curated'), ('day_trip', 'Day Trip')], default='curated', max_length=10, verbose_name='type')),
                ('date', models.DateField(blank=True, help_text='Date of the trip/shoot.', null=True, verbose_name='date')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='photologue.gallery', verbose_name='gallery')),
            ],
            options={
                'verbose_name': 'gallery extension',
                'verbose_name_plural': 'gallery extensions',
            },
        ),
    ]
