# Generated by Django 6.0.4 on 2026-04-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photoextension_web_image_galleryextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoextension',
            name='cc_license',
            field=models.BooleanField(default=False, help_text='Apply Creative Commons Attribution-NonCommercial-ShareAlike license and watermark.', verbose_name='CC BY-NC-SA license'),
        ),
    ]
