# Generated by Django 6.0.4 on 2026-04-28 12:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('markdown', 0), ('raw_html', 1), ('photo', 4), ('gallery', 7)], block_lookup={0: ('wagtailmarkdown.blocks.MarkdownBlock', (), {}), 1: ('wagtail.blocks.RawHTMLBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Slug of the photologue photo to embed.'}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('photo_slug', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Slug of the photologue gallery to embed.'}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 columns'), ('3', '3 columns'), ('4', '4 columns')]}), 7: ('wagtail.blocks.StructBlock', [[('gallery_slug', 5), ('columns', 6)]], {})}),
        ),
    ]
