# Generated by Django 6.0.4 on 2026-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='creator',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
