apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress-dev
  namespace: marco-silva
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django
                port:
                  number: 80
